### ISSUE TITLE
search caps for the push buttons

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-hardware#2]
Currently we only have the bare bone buttons. Caps would increase the size of the contact surface and may color code actuators. The buttons we use are from LCSC - part number [C455235](https://lcsc.com/product-detail/Tactile-Switches_XUNPU-TS-1003T-26_C455235.html)

![C455235 image](https://assets.lcsc.com/images/szlcsc/96x96/20200102_XUNPU-TS-1003T-26_C455235_front.jpg)

**Comment by M6QF** [comment]
These (1) caps should fit pretty well.

(1) https://www.amazon.de/dp/B0749KNQNH/ref=cm_sw_em_r_mt_dp_9HC9FbEHQE5Q2?_encoding=UTF8&psc=1

**Comment by derikon** [comment]
These are just the caps: https://www.amazon.de/Ils-Mischfarben-taktile-Knopf-Kappen-12x12x7-3mm-Takt-Schalter/dp/B07DP32Z3Q/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=taktiler+knopf+kappen&qid=1610205045&sr=8-3

**Comment by derikon** [comment]
@M6QF: If we use another type of switch we don't need additional caps.

TC-1103 series: https://lcsc.com/product-detail/Tactile-Switches_XKB-Connectivity-TC-1103-B-C_C480294.html

I like the TC-1103-B-C.
