### ISSUE TITLE
 add PDFs of schematics and PCB layout

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-hardware#3]
Currently we only have the project files for the PCB (dev board v.0.2). Would be nice to have "rendered" PDFs too.

**Comment by M6QF** [comment]
I updated the schematic. Please take a look and check all connections.

- All PWM pins are used -> 2x ULN and 16 motor pins (8 are effectively used)
- The buzzer is connected to IO4
- Breakout pins (2x7) added
- ESP pin connections changed according to the new breakout pin image.
- OLED polarity (VCC GND) swapped

[Schematic_TactJam_Release.pdf](https://github.com/TactileVision/TactJam-hardware/files/5788033/Schematic_TactJam_Release.pdf)

**Comment by derikon** [comment]
@M6QF please push the files to the **develop** branch. Afterwards I will review the schematic. Thanks
