### ISSUE TITLE
search caps for rotary switches

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-hardware#7]
Caps would increase the usability and clearly indicate the current position. The switches we use are from LCSC - part number [C370986](https://lcsc.com/product-detail/Coded-Rotary-Switches_ALPSALPINE-EC11E183440C_C370986.html)

![C370986 image](https://assets.lcsc.com/images/szlcsc/96x96/20190220_ALPSALPINE-EC11E183440C_C370986_front.jpg)

**Comment by M6QF** [comment]
Aren't the switches the following?
Potentiometer:   C209779
Rotary switches: C255511

Regardless, we should rather use narrow caps like this one:
https://www.reichelt.de/de/en/potentiometer-knob-for-axis-6-4-5-mm-black-knopf-10-150e-p73960.html?&nbc=1&trstct=lsbght_sldr::73959

According to the datasheet (1) the operation part details (p. 151) are 6 and 4.5mm respectively.

(1) https://datasheet.lcsc.com/szlcsc/1810110921_ALPSALPINE-SRBV131502_C255511.pdf
